### PR TITLE
Make Grammar Tweaks to Hack Nashville Post

### PR DESCRIPTION
**Pull request by mmccroskey**
@sciurus @jcockhren @leejones @edubkendo I went a little grammar crazy, but here are all the tweaks. Happy to hear thoughts.

### CODE REVIEW

**Comment by mmccroskey** [comment]
Also, in retrospect, should have broken this up into a commit per mini-post. Sorry about that.

**Comment by sciurus** [comment]
There is no Thought, only MERGE.

**Comment by leejones** [comment]
:+1:

**Comment by jcockhren** [comment]
thanks @mmccroskey!

**Pull request merged**
