### PR TITLE
Moving from hackpackers to engineering.lonelyplanet.com

### PR DESCRIPTION
**Pull request by mriddle**

### CODE REVIEW

**Comment by leejones** [comment]
make it tso

**Comment by mriddle** [comment]
That picture is amazing and I shall

**Comment by mriddle** [comment]
Updated Route53

Not sure what we should do about lpengineering.wordpress.com

**Comment by TimMoore** [comment]
:clap: 

I'm still getting the WordPress site when I load http://engineering.lonelyplanet.com/, but I assume that's a matter of DNS TTL.

**Comment by mriddle** [comment]
Yeah it's due to DNS TTL. Hope you see it soon :hamster:

**Pull request merged**
