### PR TITLE
look & feel updates

### PR DESCRIPTION
**Pull request by bentedder**
Some look & feel updates. I've curl'ed in rizzo's /modern services, save them in the _includes folder, and then they are built when jekyll builds. Here's a preview. Suggestions/comments/updates welcome. Not
screenshot 2014-04-08 13 19 46

### CODE REVIEW

**Comment by mriddle** [comment]
This looks great, nice work @bentedder !

**Comment by mriddle** [comment]
We could setup a Jenkins build for this repository so that when a change is made Jenkins runs the curl command to ensure Rizzo remains up to date

**Comment by mriddle** [comment]
Separate issues: 
- We should remove the About Us link. It's currently focused on the Melbourne team. We should make it more generic
- Should we point to recruiter box for the 'now hiring' link?

The side nav looks different when viewing a post:

Home:
screen shot 2014-04-08 at 1 37 36 pm

In Post:
screen shot 2014-04-08 at 1 37 27 pm

**Comment by vinbarnes** [comment]
:sparkles:

**Comment by TimMoore** [comment]
Nice!

I hope we can find a good banner image, too. It looks a bit sterile with just text.

**Comment by vinbarnes** [comment]
> I hope we can find a good banner image, too. It looks a bit sterile with just text.

I like @TimMoore 's style.

**Comment by mriddle** [comment]
Spoke to @Adambequiet and he shared some wisdom. The Planeteer blog is undergoing a facelift and we can ride of that. Image below.

We could set us apart with a cool icon, like some broken thick rim glasses with tape holding them together. _idea shamelessly stolen from Adam_

planeteer_landing_option2

**Comment by leejones** [comment]
:+1: I say :shipit: as is and then iterate on the suggestions above.

**Comment by Adambequiet** [comment]
I agree.  real good.

**Comment by mriddle** [comment]
If people are happy with my changes then lets :ship: 

I fixed the UI issue, removed the About us section and updated the jobs link to point to recruiter box

**Comment by mriddle** [comment]
@bentedder Are you happy to :ship: this?

**Comment by textgoeshere** [comment]
:+1: from me

**Pull request merged**
